{
  "timestamp": "2025-08-11T13:50:44.034Z",
  "backupAnalysis": {
    "backups": [],
    "summary": {
      "totalBackups": 0
    }
  },
  "gitAnalysis": {
    "error": "Erreur git log: '%an' n'est pas reconnu en tant que commande interne\r\nou externe, un programme exï¿½cutable ou un fichier de commandes.\r\n",
    "analysisDate": "2025-08-11T13:50:44.032Z"
  },
  "summary": {
    "totalBackups": 0,
    "totalCommits": 0,
    "relevantCommits": 0
  }
}